#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/majors/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
keepassxc &
picom &

{
  sleep 1
  xscreensaver &
  $HOME/.local/bin/autorandr -c
  $HOME/.fehbg
} &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.


exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/majors/.fluxbox/log"
