#!/usr/bin/env bash

POLKIT_PATHS=(
  /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
  /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
)

for path in "${POLKIT_PATHS[@]}"
do
  if [[ -x $path ]]; then
    $path &
  fi
done
