#!/bin/sh

CONFIG_DIR=$HOME/.config
WALLPAPER_SYMLINK=$CONFIG_DIR/wallpaper
WALLPAPER_PATH=$1

FEH_COMMAND=`which feh`

# check that feh is installed
if [ -z "$FEH_COMMAND" ]; then
  echo "Please install feh" >&2
  exit
fi

# check we were given a path
if [ -z $WALLPAPER_PATH ]; then
  echo "Please provide a path to an image file" >&2
  exit
fi

# check that the file exists
if [ ! -f $WALLPAPER_PATH ]; then
  echo "$WALLPAPER_PATH is not a valid file" >&2
  exit
fi

# create the config dir if it doesn't exist
if [ ! -d $CONFIG_DIR ]; then
  mkdir -p $CONFIG_DIR
fi

# unlink current symlink
if [ -e $WALLPAPER_SYMLINK ]; then
  if [ ! -L $WALLPAPER_SYMLINK ]; then
    echo "$WALLPAPER_SYMLINK is not a symlink. Stopping." >&2
    exit
  fi
  unlink $WALLPAPER_SYMLINK
fi

# create new symlink
ln -s $WALLPAPER_PATH $WALLPAPER_SYMLINK

# update wallpaper
$FEH_COMMAND --bg-scale $WALLPAPER_SYMLINK
