;-------------------------
; Catppuccin Mocha Palette
; Maintainer: justTOBBI
;--------------------------

[colors]
transparent = #FF00000
purple = #a277ff
purple_dark = #29263c
green = #61ffca
orange = #ffca85
pink = #f694ff
blue = #82e2ff
red = #ff6767
white = #edecee
gray = #6d6d6d
black = #15141b
foreground = #edecee
background = #15141b
